version: "3.8"
services:
  cmp-produtos:
    extends:
      file: ./componente-produtos/docker-compose.yaml
      service: cmp-produtos
    image: entityblackhawk/cmp-produtos:latest
    networks:
        - network-produtos
        - network-app

  db-produtos:
    extends:
      service: db-produtos
      file: ./componente-produtos/docker-compose.yaml
    networks:
      - network-produtos

  cmp-vendas:
    extends:
      file: ./componente-vendas/docker-compose.yaml
      service: cmp-vendas
    environment:
      - PRODUCT_API_URL=http://cmp-produtos:8080
    expose:
      - "8080:8080"
    networks:
        - network-vendas
        - network-app

  db-vendas:
    extends:
      service: db-vendas
      file: ./componente-vendas/docker-compose.yaml
    networks:
      - network-vendas

networks:
  network-app:
    driver: bridge

  network-vendas:
    driver: bridge

  network-produtos:
    driver: bridge