version: "3.8"
services:
  cmp-produtos:
    extends:
      file: ./docker-compose.yaml
      service: cmp-produtos
    ports:
      - "8081:8080"

  db-produtos:
    extends:
      service: db-produtos
      file: ./docker-compose.yaml
    ports:
      - "5433:5432"

  cmp-vendas:
    extends:
      file: ./docker-compose.yaml
      service: cmp-vendas
    ports:
      - "8080:8080"
  db-vendas:
    extends:
      service: db-vendas
      file: ./docker-compose.yaml
    ports:
      - "5432:5432"

  cmp-ecommerce:
    extends:
      file: ./docker-compose.yaml
      service: cmp-ecommerce
    ports:
      - "8083:8080"

  db-ecommerce:
    extends:
      service: db-ecommerce
      file: ./docker-compose.yaml
    ports:
      - "5434:5432"

  rabbitmq:
    extends:
      service: rabbitmq
      file: ./docker-compose.yaml
    ports:
      - "5672:5672" # Porta para conexão de aplicações

networks:
  network-app:
    driver: bridge

  network-vendas:
    driver: bridge

  network-produtos:
    driver: bridge

  network-ecommerce:
    driver: bridge
