version: "3.8"
services:
  cmp-produtos:
    extends:
      file: ./componente-produtos/docker-compose.yaml
      service: cmp-produtos
    image: entityblackhawk/cmp-produtos:latest
    networks:
        - network-produtos
        - network-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cmp-produtos:8080/product/getAll"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_interval: 10s

  db-produtos:
    extends:
      service: db-produtos
      file: ./componente-produtos/docker-compose.yaml
    networks:
      - network-produtos

  cmp-vendas:
    extends:
      file: ./componente-vendas/docker-compose.yaml
      service: cmp-vendas
    environment:
      - PRODUCT_API_URL=http://cmp-produtos:8080
    ports:
      - "8080:8080"
    networks:
        - network-vendas
        - network-app
    depends_on:
      cmp-produtos:
        condition: service_healthy

  db-vendas:
    extends:
      service: db-vendas
      file: ./componente-vendas/docker-compose.yaml
    networks:
      - network-vendas

networks:
  network-app:
    driver: bridge

  network-vendas:
    driver: bridge

  network-produtos:
    driver: bridge